export function getElements() {
  return {
    mainNav: document.getElementById("mainNav"),
    views: document.querySelectorAll(".view"),
    authView: document.querySelector("#authView"),
    appShell: document.querySelector("#appShell"),
    registerModal: document.querySelector("#registerModal"),
    openRegisterModalBtn: document.querySelector("#openRegisterModalBtn"),
    closeRegisterModalBtn: document.querySelector("#closeRegisterModalBtn"),
    loginForm: document.querySelector("#loginForm"),
    loginEmail: document.querySelector("#loginEmail"),
    loginPassword: document.querySelector("#loginPassword"),
    registerForm: document.querySelector("#registerForm"),
    registerTenant: document.querySelector("#registerTenant"),
    registerName: document.querySelector("#registerName"),
    registerEmail: document.querySelector("#registerEmail"),
    registerPassword: document.querySelector("#registerPassword"),
    logoutButton: document.querySelector("#logoutButton"),
    accountName: document.querySelector("#accountName"),
    tenantName: document.querySelector("#tenantName"),
    accountRole: document.querySelector("#accountRole"),
    adminNav: document.querySelector("#adminNav"),
    accountView: document.querySelector("#accountView"),
    userForm: document.querySelector("#userForm"),
    csvForm: document.querySelector("#csvForm"),
    csvFile: document.querySelector("#csvFile"),
    userName: document.querySelector("#userName"),
    userEmail: document.querySelector("#userEmail"),
    userPassword: document.querySelector("#userPassword"),
    userRole: document.querySelector("#userRole"),
    userList: document.querySelector("#userList"),
    selectAllUsers: document.querySelector("#selectAllUsers"),
    deleteSelectedUsers: document.querySelector("#deleteSelectedUsers"),
    form: document.querySelector("#assessmentForm"),
    createManualAssessment: document.querySelector("#createManualAssessment"),
    assessmentList: document.querySelector("#assessmentList"),
    assessmentCount: document.querySelector("#assessmentCount"),
    studentSelect: document.querySelector("#studentAssessmentSelect"),
    studentDashboard: document.querySelector("#studentDashboard"),
    studentAssessmentGrid: document.querySelector("#studentAssessmentGrid"),
    studentClassFilter: document.querySelector("#studentClassFilter"),
    monitorClassFilter: document.querySelector("#monitorClassFilter"),
    monitorRangeFilter: document.querySelector("#monitorRangeFilter"),
    trendAssessmentCount: document.querySelector("#trendAssessmentCount"),
    downloadClassCsvBtn: document.getElementById("downloadClassCsvBtn"),
    backToDashboard: document.querySelector("#backToDashboard"),
    studentEmpty: document.querySelector("#studentEmpty"),
    studentWorkspace: document.querySelector("#studentWorkspace"),
    questionProgress: document.querySelector("#questionProgress"),
    activeDifficulty: document.querySelector("#activeDifficulty"),
    activeQuestion: document.querySelector("#activeQuestion"),
    activeHint: document.querySelector("#activeHint"),
    activeOutcome: document.querySelector("#activeOutcome"),
    activeRubric: document.querySelector("#activeRubric"),
    recordButton: document.querySelector("#recordButton"),
    recorderPanel: document.querySelector("#recorderPanel"),
    recordStatus: document.querySelector("#recordStatus"),
    recordTimer: document.querySelector("#recordTimer"),
    volumeIndicator: document.querySelector("#volumeIndicator"),
    testMicButton: document.querySelector("#testMicButton"),
    micStatus: document.querySelector("#micStatus"),
    micDiagnostics: document.querySelector("#micDiagnostics"),
    answerText: document.querySelector("#answerText"),
    prevQuestion: document.querySelector("#prevQuestion"),
    saveAnswer: document.querySelector("#saveAnswer"),
    answerMap: document.querySelector("#answerMap"),
    studentName: document.querySelector("#studentName"),
    finishAssessment: document.querySelector("#finishAssessment"),
    resultPanel: document.querySelector("#resultPanel"),
    evaluationLoadingModal: document.querySelector("#evaluationLoadingModal"),
    submissionCount: document.querySelector("#submissionCount"),
    submissionList: document.querySelector("#submissionList"),
    studentHistoryList: document.querySelector("#studentHistoryList"),
    classAverage: document.querySelector("#classAverage"),
    trendList: document.querySelector("#trendList"),
    seedDemo: document.querySelector("#seedDemo"),
    resetData: document.querySelector("#resetData"),
    recommendOutcomes: document.querySelector("#recommendOutcomes"),
    recommendRubric: document.querySelector("#recommendRubric"),
    topic: document.querySelector("#topic"),
    outcomes: document.querySelector("#outcomes"),
    rubric: document.querySelector("#rubric"),
    difficulty: document.querySelector("#difficulty"),
    timeLimit: document.querySelector("#timeLimit"),
    timerDisplay: document.querySelector("#timerDisplay"),
    examples: document.querySelector("#examples"),
    questionCount: document.querySelector("#questionCount"),
    classSelect: document.querySelector("#classSelect"),
    classPanel: document.querySelector("#classPanel"),
    classForm: document.querySelector("#classForm"),
    classNameInput: document.querySelector("#className"),
    classList: document.querySelector("#classList"),
    bulkAddClassSelect: document.querySelector("#bulkAddClassSelect"),
    bulkAddEmails: document.querySelector("#bulkAddEmails"),
    bulkAddButton: document.querySelector("#bulkAddButton"),
    bulkAddClear: document.querySelector("#bulkAddClear"),
    bulkAddCsvFile: document.querySelector("#bulkAddCsvFile"),
    bulkAddCsvUpload: document.querySelector("#bulkAddCsvUpload"),
    bulkAddCsvTemplate: document.querySelector("#bulkAddCsvTemplate"),
    joinClassForm: document.querySelector("#joinClassForm"),
    joinCode: document.querySelector("#joinCode"),
    pendingJoinList: document.querySelector("#pendingJoinList"),
    approvedMemberList: document.querySelector("#approvedMemberList"),
    memberSearchInput: document.querySelector("#memberSearchInput"),
    memberPaginationContainer: document.querySelector("#memberPaginationContainer"),
    memberPrevBtn: document.querySelector("#memberPrevBtn"),
    memberNextBtn: document.querySelector("#memberNextBtn"),
    memberPageInfo: document.querySelector("#memberPageInfo"),
    memberCountText: document.querySelector("#memberCountText"),
    studentJoinClassForm: document.querySelector("#studentJoinClassForm"),
    studentJoinCode: document.querySelector("#studentJoinCode"),
    studentClassList: document.querySelector("#studentClassList"),
    questionEditor: document.querySelector("#questionEditor"),
    editableQuestionList: document.querySelector("#editableQuestionList"),
    addManualQuestion: document.querySelector("#addManualQuestion"),
    saveQuestionSet: document.querySelector("#saveQuestionSet"),
    improveQuestionSet: document.querySelector("#improveQuestionSet"),
    wizardSteps: document.querySelectorAll(".wizard-step"),
    wizardPanels: document.querySelectorAll(".wizard-panel"),
    wizardToQuestions: document.querySelector("#wizardToQuestions"),
    wizardBackToContext: document.querySelector("#wizardBackToContext"),
    wizardToReview: document.querySelector("#wizardToReview"),
    wizardBackToQuestions: document.querySelector("#wizardBackToQuestions"),
    reviewSummary: document.querySelector("#reviewSummary"),
    simulatorWidget: document.querySelector("#simulatorWidget"),
    simulatorToggle: document.querySelector("#simulatorToggle"),
    simulatorPanel: document.querySelector("#simulatorPanel"),
    simulatorClose: document.querySelector("#simulatorClose"),
    simulatorTenantList: document.querySelector("#simulatorTenantList"),
    disableManualTyping: document.querySelector("#disableManualTyping"),
    oralExamEnabled: document.querySelector("#oralExamEnabled"),
    editDisableManualTyping: document.querySelector("#editDisableManualTyping"),
    editOralExamEnabled: document.querySelector("#editOralExamEnabled"),
    allowRetakes: document.querySelector("#allowRetakes"),
    editAllowRetakes: document.querySelector("#editAllowRetakes"),
    recordInstructions: document.querySelector("#recordInstructions"),
    observabilityView: document.querySelector("#observabilityView"),
    telemetryTotalCalls: document.querySelector("#telemetryTotalCalls"),
    telemetryErrorRate: document.querySelector("#telemetryErrorRate"),
    telemetryLatency: document.querySelector("#telemetryLatency"),
    telemetryTokens: document.querySelector("#telemetryTokens"),
    telemetryTokenBreakdown: document.querySelector("#telemetryTokenBreakdown"),
    telemetryCost: document.querySelector("#telemetryCost"),
    telemetryCacheEfficiency: document.querySelector("#telemetryCacheEfficiency"),
    telemetryCacheSavings: document.querySelector("#telemetryCacheSavings"),
    cacheSavingsPercentRing: document.querySelector("#cacheSavingsPercentRing"),
    cacheSavedTokensVal: document.querySelector("#cacheSavedTokensVal"),
    cacheSavedCostVal: document.querySelector("#cacheSavedCostVal"),
    sysMemoryHeap: document.querySelector("#sysMemoryHeap"),
    sysMemoryTotal: document.querySelector("#sysMemoryTotal"),
    sysCpuUsage: document.querySelector("#sysCpuUsage"),
    sysCpuSystem: document.querySelector("#sysCpuSystem"),
    sysUptime: document.querySelector("#sysUptime"),
    sysNodeVersion: document.querySelector("#sysNodeVersion"),
    telemetryLogList: document.querySelector("#telemetryLogList"),
    refreshTelemetryBtn: document.querySelector("#refreshTelemetryBtn"),
    complaintView: document.querySelector("#complaintView"),
    complaintList: document.querySelector("#complaintList"),
    complaintCount: document.querySelector("#complaintCount"),
    complaintNavBadge: document.querySelector("#complaintNavBadge"),
    complaintNotification: document.querySelector("#complaintNotification"),
    apiKeyName: document.querySelector("#apiKeyName"),
    createApiKeyBtn: document.querySelector("#createApiKeyBtn"),
    apiKeyResult: document.querySelector("#apiKeyResult"),
    apiKeyValue: document.querySelector("#apiKeyValue"),
    apiKeyList: document.querySelector("#apiKeyList"),
    apiKeysView: document.querySelector("#apiKeysView"),
  };
}

export function setButtonLoading(button, loading, loadingText, defaultText) {
  button.disabled = loading;
  button.classList.toggle("is-loading", loading);
  button.setAttribute("aria-busy", String(loading));
  button.textContent = loading ? loadingText : defaultText;
}

export function showEmpty(container, className, message) {
  container.className = className;
  container.setAttribute("role", "status");
  container.innerHTML = `
    <span class="empty-state-icon" aria-hidden="true">○</span>
    <div>
      <strong>Belum ada data</strong>
      <p>${message}</p>
    </div>
  `;
}
